booking/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = "booking"
urlpatterns = [
    url(r"^$", views.booking_main_page, name = "main_page"),
    url(r"^orders/$", views.booking_orders_page, name = "orders_page"),
    url(r"^catalogs/$", views.booking_catalogs_page, name = "catalogs_page"),
    url(r"^orders/editor/$", views.booking_order_editor, name = "order_editor"),
    url(r"^books/services/$", views.booking_books_services, name = "books_services"),
    url(r"^orders/services/$", views.booking_orders_services, name = "orders_services"),
    url(r"^catalogs/services/$", views.booking_catalogs_services, name = "catalogs_services"),
    url(r"^login/$", auth_views.login, {"template_name": "booking/login.html"}, name = "login_page"),
    url(r"^logout/$", views.booking_logout, name = "logout_page"),
]

zakaz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^zakaz/', include('booking.urls')),
    url(r'^admin/', admin.site.urls),
]

booking/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User

ORDER_STATES = (
    "В обработке",
    "Сформирован",
    "Подготовлен к экспорту в АБИС"
)

class SerializedModel:
    def serialize(self):
        return serialize(self)

def serialize(object):
    serialized = dict()
    for attr in object.__serialize__():
        value = getattr(object, attr)
        serialized[attr] = serialize(value) if hasattr(value, "__serialize__") else value
    return serialized

class Provider(models.Model, SerializedModel):
    name = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    location = models.CharField(max_length=64)
    is_publisher = models.BooleanField(default=True)

    def __serialize__(self):
        return ("id", "name", "email", "location", "is_publisher")

    def __str__(self):
        return str(self.serialize())

class Catalog(models.Model, SerializedModel):
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    refresh_date = models.DateTimeField(auto_now=True)
    
    def __serialize__(self):
        return ("id", "provider")
    
    def serialize(self):
        catalog = super().serialize()
        catalog["refresh_date"] = datetime.strftime(self.refresh_date, "%d.%m.%Y %H:%M:%S")
        catalog["items"] = Book.objects.filter(provider = self.provider).count()
        return catalog
    
    def __str__(self):
        return str(self.serialize())

class Book(models.Model, SerializedModel):
    year = models.PositiveSmallIntegerField(default=0)
    isbn = models.CharField(default="", max_length=64)
    pages = models.PositiveSmallIntegerField(default=0)
    price = models.PositiveSmallIntegerField(default=0)
    name = models.CharField(default="", max_length=128)
    authors = models.CharField(default="", max_length=128)
    publication = models.PositiveSmallIntegerField(default=0)
    volume_name = models.CharField(default="", max_length=64)
    volume_number = models.PositiveSmallIntegerField(default=0)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)

    def __serialize__(self):
        return ("id", "year", "pages", "price", "isbn", "name", "authors", 
                "publication", "volume_name", "volume_number", "provider")
    
    def __hash__(self):
        return hash(self.name)
    
    def __eq__(self, o):
        return hash(self) == hash(o)

    def __str__(self):
        return str(self.serialize())

class Order(models.Model, SerializedModel):
    year = models.PositiveSmallIntegerField(default=0)
    state = models.PositiveSmallIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)

    def __serialize__(self):
        return ("id", "year", "state", "provider")

    def serialize(self):
        order_price = 0
        order_items = 0
        order_books = []
        order = super().serialize()
        for ordered_book in OrderedBook.objects.filter(order = self):
            order_books.append(ordered_book.serialize())
            order_price += ordered_book.price * ordered_book.amount
            order_items += ordered_book.amount
        order["items"] = order_items
        order["books"] = order_books
        order["price"] = order_price
        return order

    def __str__(self):
        return str(self.serialize())

class OrderedBook(models.Model, SerializedModel):
    price = models.PositiveSmallIntegerField(default=0)
    amount = models.PositiveSmallIntegerField(default=0)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __serialize__(self):
        return ("id", "book", "order", "amount", "price")

    def __str__(self):
        return str(self.serialize())

booking/views.py
from django.contrib import auth
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .models import Provider
from .models import ORDER_STATES

from .services import BooksServices
from .services import OrdersServices
from .services import CatalogsServices

ORDER_STATES = list(enumerate(ORDER_STATES, 1))

@login_required
def booking_logout(request):
    auth.logout(request)
    return redirect("/zakaz/login")

@login_required
def booking_main_page(request):
    user = request.user
    providers = Provider.objects.all()
    return render(request, "booking/main.html", context = {
        "user": user,
        "states": ORDER_STATES,
        "providers": providers,
    })

@login_required
def booking_orders_page(request):
    user = request.user
    providers = Provider.objects.all()
    return render(request, "booking/orders.html", context = {
        "user": user,
        "states": ORDER_STATES,
        "providers": providers
    })

@login_required
def booking_catalogs_page(request):
    user = request.user
    providers = Provider.objects.all()
    return render(request, "booking/catalogs.html", context = {
        "user": user,
        "providers": providers,
    })

@login_required
def booking_order_editor(request):
    user = request.user
    providers = Provider.objects.all()
    order_id = int(request.GET.get("order_id", 0))
    return render(request, "booking/order_editor.html", context = {
        "user": user,
        "states": ORDER_STATES,
        "order_id": order_id,
        "providers": providers
    })

@login_required
def booking_books_services(request):
    return BooksServices(request).exec()

@login_required
def booking_orders_services(request):
    return OrdersServices(request).exec()

@login_required
def booking_catalogs_services(request):
    return CatalogsServices(request).exec()

booking/templates/booking/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ZAKAZ</title>
    <link href="{% static 'booking/lib/bootstrap-4.0.0-alpha.6-dist/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'booking/base/base.css' %}" rel="stylesheet">
	{% block corestyles %}{% endblock %}
	{% block userstyles %}{% endblock %}
</head>
<body>
	<div class="container">
		<div class="header clearfix">
			<nav>
				{% block navigation %}
				{% endblock %}
			</nav>
			<h3 class="logo text-muted"><img src="{% static 'booking/img/logo.svg' %}" alt="ZAKAZ" /></h3>
		</div>
		<div class="marketing row row-offcanvas row-offcanvas-right">{% block marketing %}{% endblock %}</div>
		<footer class="footer"><p>&copy; ИУ7-83</p></footer>
	</div>
	{% block body %}{% endblock %}
	<script src="{% static 'booking/lib/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'booking/lib/tether-1.3.3/js/tether.min.js' %}"></script>
	<script src="{% static 'booking/lib/bootstrap-4.0.0-alpha.6-dist/js/bootstrap.min.js' %}"></script>
	{% block corescripts %}{% endblock %}
	{% block userscripts %}{% endblock %}
</body>
</html>

booking/templates/booking/booking.html
{% extends "booking/base.html" %}
{% block corestyles %}
<link href="{% static 'booking/booking/booking.css' %}" rel="stylesheet">
{% endblock %}
{% block corescripts %}
<script src="{% static 'booking/lib/sprintf.min.js' %}"></script>
<script src="{% static 'booking/booking/booking.js' %}"></script>
<script src="{% static 'booking/base/base.js' %}"></script>
<script>
	var staticUrl = "{% static '' %}";
	var orderUrl = "{% url 'booking:orders_page' %}";
	var orderEditorUrl = "{% url 'booking:order_editor' %}";
	var booksServicesUrl = "{% url 'booking:books_services' %}";
	var ordersServicesUrl = "{% url 'booking:orders_services' %}";
	var catalogsServicesUrl = "{% url 'booking:catalogs_services' %}";
</script>
<script>
var orderStates = {
    {% for pos, state in states %}
    {{ pos }}: "{{ state }}",
    {% endfor %}
};
</script>
{% endblock %}
{% block navigation %}
<ul class="nav nav-pills float-right">
	{% block links %}
	{% endblock %}
	<li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
		aria-haspopup="true" aria-expanded="false">{{ user.last_name }} {{ user.first_name|slice:":1" }}.</a>
		<div class="dropdown-menu">
			<a class="dropdown-item disabled" href="#">Настройки</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" href="{% url 'booking:logout_page' %}">Выход</a>
		</div>
	</li>
</ul>
{% endblock %}

booking/templates/booking/catalogs.html
{% extends "booking/booking.html" %}
{% block userstyles %}
<link href="{% static 'booking/catalogs/catalogs.css' %}" rel="stylesheet">
{% endblock %}
{% block links %}
<li class="nav-item"><a class="nav-link" href="{% url 'booking:main_page' %}">Книги</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'booking:orders_page' %}">Заказы</a></li>
<li class="nav-item"><a class="nav-link active" href="{% url 'booking:catalogs_page' %}">Издательства</a></li>
{% endblock %}
{% block marketing %}
<table id="catalogs-table" class="table table-hover">
    <thead class="thead-default">
        <th width="50%">Издательство</th>
        <th width="20%">Кол - во элементов</th>
        <th width="25%">Последнее обновление</th>
        <th width="5%"></th>
    </thead>
    <tbody></tbody>
</table>
{% endblock %}
{% block body %}
<div class="modal fade" id="catalog-refresh-dialog" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body"><form>
                <div class="form-group">
                    <label class="form-control-label" for="refresh-progress">Выполняется обновление каталога</label>
                    <div class="progress">
                        <div id="refresh-progress" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                    </div>
                </div>
            </form></div>
        </div>
    </div>
</div>
{% endblock %}
{% block userscripts %}
<script src="{% static 'booking/catalogs/catalogs.js' %}"></script>
{% endblock %}

booking/templates/booking/login.html
{% extends "booking/base.html" %}
{% block userstyles %}
<link href="{% static 'booking/login/login.css' %}" rel="stylesheet">
{% endblock %}
{% block marketing %}
<form class="form-signin" method="post">
    {% csrf_token %}
    <input type="username" name="username" id="input-username" class="form-control" placeholder="Логин" required autofocus>
    <input type="password" name="password" id="input-password" class="form-control" placeholder="Пароль" required>
    <button class="btn btn-lg btn-outline-primary btn-block" type="submit">Войти</button>
    <input type="hidden" name="next" value="{{ next }}" />
</form>
{% endblock %}

booking/templates/booking/main.html
{% extends "booking/booking.html" %}
{% block userstyles %}
<link href="{% static 'booking/main/main.css' %}" rel="stylesheet">
{% endblock %}
{% block links %}
<li class="nav-item"><a class="nav-link active" href="#">Книги</a></li>
<li class="nav-item"><a class="nav-link" href="#" data-toggle="modal" data-target="#orders-dialog">Заказы</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'booking:catalogs_page' %}">Издательства</a></li>
{% endblock %}
{% block marketing %}
<div class="col-12 col-md-9">
    <table id="books-table" class="table table-hover">
        <thead class="thead-default">
        <th width="75%">Описание книги</th>
        <th width="15%">Цена</th>
        <th width="10%"></th>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="col-6 col-md-3 sidebar-offcanvas">
    <button type="button" class="btn btn-success add-new-button" data-toggle="modal" data-target="#new-book-dialog">Добавить новую книгу</button>
    <div class="filters list-group">
        <form class="list-group-item">
            <div class="form-group">
                <label for="filter-provider">Издательство</label>
                <select id="filter-provider" class="custom-select form-control">
                    <option value="0">Все</option>
                    {% for provider in providers %}
                    <option value="{{ provider.id }}">{{ provider.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="filter-authors">Автор</label>
                <input id="filter-authors" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label for="filter-name">Название</label>
                <input id="filter-name" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label for="filter-year">Год издания</label>
                <input id="filter-year" type="number" class="form-control"/>
            </div>
            <div style="min-width: 100%" class="btn-group-vertical" role="group">
                <button id="apply-books-filter" type="button" class="btn btn-outline-primary" onclick="applyBooksFilter()">Применить</button>
                <button type="button" class="btn btn-outline-primary" onclick="resetBooksFilter()">Сбросить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body %}
<div class="modal fade" id="orders-dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table id="orders-table" class="table">
                    <thead class="thead-default">
                        <th width="55%">Заказы</th>
                        <th width="20%">Кол - во книг</th>
                        <th width="20%">Стоимость</th>
                        <th width="5%"></th>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-primary" onclick="openOrdersPage()">Редактирование заказов</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="new-book-dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"><form>
                <div class="row">
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-year">Год</label>
                        <input id="new-book-year" type="number" class="form-control" />
                    </div>
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-isbn">ISBN</label>
                        <input id="new-book-isbn" type="text" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-pages">Количество страниц</label>
                        <input id="new-book-pages" type="number" class="form-control" />
                    </div>
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-price">Стоимость (руб.)</label>
                        <input id="new-book-price" type="number" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-name">Название</label>
                        <input id="new-book-name" type="text" class="form-control" />
                    </div>
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-authors">Авторы</label>
                        <input id="new-book-authors" type="text" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-publication">Том</label>
                        <input id="new-book-publication" type="number" class="form-control" />
                    </div>
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-volume-name">Название издания</label>
                        <input id="new-book-volume-name" type="text" class="form-control" />
                    </div>
                </div>
                <div class="row">
                    <div class="col form-group">
                        <label class="form-control-label" for="new-book-volume-number">Номер издания</label>
                        <input id="new-book-volume-number" type="number" class="form-control" />
                    </div>
                    <div class="col form-group">
                        <label for="new-book-provider">Издательство</label>
                        <select id="new-book-provider" class="custom-select form-control">
                        {% for provider in providers %}
                            <option value="{{ provider.id }}">{{ provider.name }}</option>
                        {% endfor %}
                        </select>
                    </div>
                </div>
            </form></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-primary" onclick="createNewBook()">Добавить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block userscripts %}
<script src="{% static 'booking/main/main.js' %}"></script>
{% endblock %}

booking/templates/booking/orders.html
{% extends "booking/booking.html" %}
{% block userstyles %}
<link href="{% static 'booking/orders/orders.css' %}" rel="stylesheet">
{% endblock %}
{% block links %}
<li class="nav-item"><a class="nav-link" href="{% url 'booking:main_page' %}">Книги</a></li>
<li class="nav-item"><a class="nav-link active" href="#">Заказы</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'booking:catalogs_page' %}">Издательства</a></li>
{% endblock %}
{% block marketing %}
<div class="col-12 col-md-9">
    <table id="orders-table" class="table table-hover">
        <thead class="thead-default">
            <th width="50%">Заказы</th>
            <th width="20%">Кол - во книг</th>
            <th width="20%">Стоимость</th>
            <th width="10%"></th>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div class="col-6 col-md-3 sidebar-offcanvas">
    <button id="add-new-order" type="button" class="btn btn-success add-new-button" onclick="openCreateOrderPopup()">Создать новый заказ</button>
    <div class="filters list-group">
        <form class="list-group-item">
            <div class="form-group">
                <label for="filter-provider">Издательство</label>
                <select id="filter-provider" class="custom-select form-control">
                    <option value="0">Все</option>
                    {% for provider in providers %}
                    <option value="{{ provider.id }}">{{ provider.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="filter-state">Статус</label>
                <select id="filter-state" class="custom-select form-control">
                    <option value="0">Все</option>
                    {% for pos, state in states %}
                    <option value="{{ pos }}">{{ state }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="filter-year">Год</label>
                <input id="filter-year" type="number" class="form-control">
            </div>
            <div style="min-width: 100%" class="btn-group-vertical" role="group">
                <button id="apply-orders-filter" type="button" class="btn btn-outline-primary" onclick="applyOrdersFilter()">Применить</button>
                <button type="button" class="btn btn-outline-primary" onclick="resetOrdersFilter()">Сбросить</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block body %}
<div class="modal fade" id="order-customize-dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"><form>
                <div class="form-group">
                    <label for="customize-order-provider">Издательство</label>
                    <select id="customize-order-provider" class="custom-select form-control" disabled="disabled">
                    {% for provider in providers %}
                        <option value="{{ provider.id }}">{{ provider.name }}</option>
                    {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="customize-order-state">Состояние</label>
                    <select id="customize-order-state" class="custom-select form-control" onchange="changeCurrentOrderState()">
                    {% for pos, state in states %}
                        <option value="{{ pos }}">{{ state }}</option>
                    {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" for="customize-order-year">Год</label>
                    <input id="customize-order-year" type="text" class="form-control" onchange="changeCurrentOrderYear()" />
                </div>
                <div class="form-group">
                    <table id="customize-order-books-table" class="table table-hover">
                        <thead class="thead-default">
                            <th width="40%">Описание книги</th>
                            <th width="20%">Цена (пост.)</th>
                            <th width="20%">Цена (собс.)</th>
                            <th width="10%">Кол - во</th>
                            <th width="10%"></th>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </form></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block userscripts %}
<script>
function openCreateOrderPopup() {
    var content = "<div class=\"add-order-popup\">" +
        "<label for=\"new-order-provider\">Выберите издательство:</label>" +
        "<select id=\"new-order-provider\" class=\"custom-select form-control\">" +
        "{% for provider in providers %}" +
        "<option value=\"{{ provider.id }}\">{{ provider.name }}</option>" +
        "{% endfor %}</select>" +
        "<div class=\"btn-group btn-group-justified\" style=\"margin-top:0.5em;min-width:100%\" role=\"group\">" + 
        "<button style=\"width: 50%\" type=\"button\" class=\"btn btn-success\" onclick=\"createEmptyOrder()\">Создать</button>" +
        "<button style=\"width: 50%\" type=\"button\" class=\"btn btn-secondary\" onclick=\"hideCreateOrderPopup()\">Отмена</button>" +
        "</div></div>";
    $("#add-new-order").popover({
        "html": true,
        "placement": "bottom",
        "content": content,
    }).popover("show").on("hide.bs.popover", function() {
        $("#add-new-order").popover("dispose");
    });
}
</script>
<script src="{% static 'booking/orders/orders.js' %}"></script>
{% endblock %}